

export const resultData = {
  instructorId: "admin",
  title: "quick test",
  description: "Admin quick test",
  img: "https://t4.ftcdn.net/jpg/02/69/09/69/360_F_269096915_ZdBDh5VK5b4moAzWWLJceXRNTA5ECJXc.jpg",
  testQuestions: [
       {
      questionText:
        "The sum of three numbers is 98. If the ratio of the first to second is 2 :3 and that of the second to the third is 5 : 8, then the second number is:",
      questionImage: "",
      questionType: "Numerical Reasoning",
      option1: "20",
      option2: "30",
      option3: "48",
      option4: "58",
      suggestions: [
        "computer science",
        "design",
        "laboratory technician",
        "accounting",
        "auditor",
        "tax consultant",
      ],

      score: 5,
      answerText: "30",
      answerIndex: 1,
    },
    {
      questionText: "Which figure is next in the series?",
      questionImage: "https://i.postimg.cc/qBFQzjQs/q1.png",
      questionType: "Abstract Reasoning",
      option1: "A",
      option2: "B",
      option3: "C",
      option4: "D",
      suggestions: [
        "computer science",
        "design",
        "law",
        "architecture",
        "animations",
        "construction",
        "carpentry",
        "laboratory technician",
        "mechanics",
      ],

      score: 5,
      answerText: "B",
      answerIndex: 1,
    },
    {
      questionText: "Which figure completes the grid?",
      questionImage: "https://i.postimg.cc/XNrmHZzg/2.png",
      questionType: "Abstract Reasoning",
      option1: "A",
      option2: "B",
      option3: "C",
      option4: "D",
      suggestions: [
        "computer science",
        "design",
        "law",
        "architecture",
        "animations",
        "construction",
        "carpentry",
        "laboratory technician",
        "mechanics",
      ],

      score: 5,
      answerText: "A",
      answerIndex: 0,
    },
    {
      questionText: "Identify the missing square.",
      questionImage: "https://i.postimg.cc/28cqzKwY/3.png",
      questionType: "Abstract Reasoning",
      option1: "A",
      option2: "B",
      option3: "C",
      option4: "D",
      suggestions: [
        "computer science",
        "design",
        "law",
        "architecture",
        "animations",
        "construction",
        "carpentry",
        "laboratory technician",
        "mechanics",
      ],

      score: 5,
      answerText: "C",
      answerIndex: 2,
    },
  ],
};
