

export const resultData = {
  instructorId: "admin",
  title: "quick test",
  description: "Admin quick test",
  img: "https://t4.ftcdn.net/jpg/02/69/09/69/360_F_269096915_ZdBDh5VK5b4moAzWWLJceXRNTA5ECJXc.jpg",
  testQuestions: [
    {
      questionText: "Find the correctly spelt word.",
      questionImage: "",
      questionType: "Spelling",
      option1: "Vetarinary",
      option2: "Veteninary",
      option3: "Vetinary",
      option4: "Veterinary",
      suggestions: [
        "Bussiness executive",
        "Reviewers",
        "Script Writers",
        "Authors",
        "Proof Readers",
        "Media Editors",
        "Public Relations",
        "Civil Service",
      ],
      score: 5,
      answerText: "Veterinary",
      answerIndex: 3,
    },
    {
      questionText: "Find the correctly spelt word.",
      questionImage: "",
      questionType: "Spelling",
      option1: "Humorous",
      option2: "saumorous",
      option3: "fmorous",
      suggestions: [
        "Bussiness executive",
        "Reviewers",
        "Script Writers",
        "Authors",
        "Proof Readers",
        "Media Editors",
        "Public Relations",
        "Civil Service",
      ],
      option4: "sfumorous",
      score: 5,
      answerText: "Humorous",
      answerIndex: 0,
    },
    {
      questionText: "Find the correctly spelt word.",
      questionImage: "",
      questionType: "Spelling",
      option1: "Aeroddrome",
      option2: "Aerodrome",
      option3: "Aerodrom",
      option4: "Aerodroe",
      suggestions: [
        "Bussiness executive",
        "Reviewers",
        "Script Writers",
        "Authors",
        "Proof Readers",
        "Media Editors",
        "Public Relations",
        "Civil Service",
      ],

      score: 5,
      answerText: "Aerodrome",
      answerIndex: 1,
    },
    {
      questionText: "Find the correctly spelt word.",
      questionImage: "",
      questionType: "Spelling",
      option1: "Acquainttance",
      option2: "Acqquaintance",
      option3: "Acquintance",
      option4: "Acquaintance",
      suggestions: [
        "Bussiness executive",
        "Reviewers",
        "Script Writers",
        "Authors",
        "Proof Readers",
        "Media Editors",
        "Public Relations",
        "Civil Service",
      ],

      score: 5,
      answerText: "Acquaintance",
      answerIndex: 3,
    },
    {
      questionText: "The small child does whatever his father was done.",
      questionImage: "",
      questionType: "Language Usage",
      option1: "has done",
      option2: "did",
      option3: "does",
      option4: "had done",
      suggestions: [
        "Seceratory",
        "Researcher",
        "Reviewer",
        "Script Writers",
        "Authors",
        "Proof Readers",
        "Editors",
        "Public Relations",
        "Civil Service",
        "Advertising",
      ],

      score: 5,
      answerText: "does",
      answerIndex: 2,
    },
    {
      questionText: "You need not come unless you want to.",
      questionImage: "",
      questionType: "Language Usage",
      option1: "You don't need to come unless you want to",
      option2: "You come only when you want to",
      option3: "You come unless you don't want to",
      option4: "You needn't come until you don't want to",
      suggestions: [
        "Seceratory",
        "Researcher",
        "Reviewer",
        "Script Writers",
        "Authors",
        "Proof Readers",
        "Editors",
        "Public Relations",
        "Civil Service",
        "Advertising",
      ],

      score: 5,
      answerText: "You don't need to come unless you want to",
      answerIndex: 0,
    },
    {
      questionText:
        "There are not many men who are so famous that they are frequently referred to by their short names only",
      questionImage: "",
      questionType: "Language Usage",
      option1: "initials",
      option2: "signatures",
      option3: "pictures",
      option4: "middle names",
      suggestions: [
        "Seceratory",
        "Researcher",
        "Reviewer",
        "Script Writers",
        "Authors",
        "Proof Readers",
        "Editors",
        "Public Relations",
        "Civil Service",
        "Advertising",
      ],

      score: 5,
      answerText: "initials",
      answerIndex: 0,
    },
    {
      questionText: "The man to who I sold my house was a cheat.",
      questionImage: "",
      questionType: "Language Usage",
      option1: "to whom I sell",
      option2: "to who I sell",
      option3: "who was sold to",
      option4: "to whom I sold ",
      suggestions: [
        "Seceratory",
        "Researcher",
        "Reviewer",
        "Script Writers",
        "Authors",
        "Proof Readers",
        "Editors",
        "Public Relations",
        "Civil Service",
        "Advertising",
      ],

      score: 5,
      answerText: "to whom I sold ",
      answerIndex: 3,
    },
    {
      questionText: "Which one is different from the other two",
      questionImage: "",
      questionType: "Clerical speed and accuracy",
      option1: "multzi zoloene frankiri",
      option2: "multizi zoloene frankiri",
      option3: "multzi zoloene frankiri",
      option4: "no difference",
      suggestions: [
        "Seceratory",
        "Researcher",
        "Computrt Science",
        "Quality Control",
        "Assembly work",
        "Proof Readers",
        "Coding",
        "Legal Execcutive",
        "Personal Assistant",
      ],

      score: 5,
      answerText: "multizi zoloene frankiri ",
      answerIndex: 1,
    },
    {
      questionText: "Which one is different from the other two",
      questionImage: "",
      questionType: "Clerical speed and accuracy",
      option1: "P.O Box 12 39 ittoqqortmiit",
      option2: "P.O Box 12 39 ittoqqortmiit ",
      option3: "P.O Box 12 39 ittoqqortmit",
      option4: "no difference",
      suggestions: [
        "Seceratory",
        "Researcher",
        "Computrt Science",
        "Quality Control",
        "Assembly work",
        "Proof Readers",
        "Coding",
        "Legal Execcutive",
        "Personal Assistant",
      ],

      score: 5,
      answerText: "P.O Box 12 39 ittoqqortmit ",
      answerIndex: 2,
    },
    {
      questionText: "Which one is different from the other two",
      questionImage: "",
      questionType: "Clerical speed and accuracy",
      option1: "industrilana grande manli",
      option2: "industrilana grande manli  ",
      option3: "industrilana grande manli",
      option4: "no difference",
      suggestions: [
        "Seceratory",
        "Researcher",
        "Computrt Science",
        "Quality Control",
        "Assembly work",
        "Proof Readers",
        "Coding",
        "Legal Execcutive",
        "Personal Assistant",
      ],

      score: 5,
      answerText: "industrilana grande manli  ",
      answerIndex: 1,
    },
    {
      questionText: "Which one is different from the other two",
      questionImage: "",
      questionType: "Clerical speed and accuracy",
      option1: "industrilana grande manli",
      option2: "industrilana grande manli  ",
      option3: "industrilana grande manli",
      option4: "no difference",
      suggestions: [
        "Seceratory",
        "Researcher",
        "Computrt Science",
        "Quality Control",
        "Assembly work",
        "Proof Readers",
        "Coding",
        "Legal Execcutive",
        "Personal Assistant",
      ],

      score: 5,
      answerText: "no difference  ",
      answerIndex: 3,
    },
    {
      questionText: "What would the 3D shape look like from above?",
      questionImage: "https://i.postimg.cc/C5YpbcLx/q1.png",
      questionType: "Space Relation",
      option1: "A",
      option2: "B",
      option3: "C",
      option4: "D",
      suggestions: [
        "photographer",
        "architect",
        "animator",
        "designer",
        "town planner",
        "industrial design",
        "interior design",
      ],

      score: 5,
      answerText: "A ",
      answerIndex: 0,
    },
    {
      questionText:
        "Which of the given shapes is a rotation of the main image?",
      questionImage: "https://i.postimg.cc/prn5nXrH/q2.png",
      questionType: "Space Relation",
      option1: "A",
      option2: "B",
      option3: "C",
      option4: "D",
      suggestions: [
        "photographer",
        "architect",
        "animator",
        "designer",
        "town planner",
        "industrial design",
        "interior design",
      ],

      score: 5,
      answerText: "D ",
      answerIndex: 3,
    },
    {
      questionText: "Which figure not is identical to the first?",
      questionImage: "https://i.postimg.cc/fL3TL2qt/q3.png",
      questionType: "Space Relation",
      option1: "A",
      option2: "B",
      option3: "C",
      option4: "D",
      suggestions: [
        "photographer",
        "architect",
        "animator",
        "designer",
        "town planner",
        "industrial design",
        "interior design",
      ],

      score: 5,
      answerText: "D ",
      answerIndex: 3,
    },
    {
      questionText: "Which figure not is identical to the first?",
      questionImage: "hhttps://i.postimg.cc/Dyhnkwhb/q4.png",
      questionType: "Space Relation",
      option1: "A",
      option2: "B",
      option3: "C",
      option4: "D",
      suggestions: [
        "photographer",
        "architect",
        "animator",
        "designer",
        "town planner",
        "industrial design",
        "interior design",
      ],

      score: 5,
      answerText: "B ",
      answerIndex: 1,
    },
    {
      questionText: "On which pole does the weight press harder?",
      questionImage: "https://i.postimg.cc/Z5FHRZCg/Q1.png",
      questionType: "Mechanical Reasoning",
      option1: "1",
      option2: "2",
      option3: "The weight presses equally on both poles",
      option4: "None",
      suggestions: [
        "construction manager",
        "carpentry",
        "quality control",
        "assembly workers",
        "maintenance workers",
        "aircraft engineer",
        "machine operative",
      ],

      score: 5,
      answerText: "2 ",
      answerIndex: 1,
    },
    {
      questionText:
        "What would be the current flowing through point X if another identical power source were to be added in parallel to the circuit? ",
      questionImage: "https://i.postimg.cc/TY5HTZjM/Q2.png",
      questionType: "Mechanical Reasoning",
      option1: "Twice as strong",
      option2: "Half as strong",
      option3: "There is no difference",
      option4: "None",
      suggestions: [
        "construction manager",
        "carpentry",
        "quality control",
        "assembly workers",
        "maintenance workers",
        "aircraft engineer",
        "machine operative",
      ],

      score: 5,
      answerText: "There is no difference ",
      answerIndex: 2,
    },
    {
      questionText: "For this balloon to stay up, the gas in the bag must be:",
      questionImage: "https://i.postimg.cc/MGpLJXdt/Q3.png",
      questionType: "Mechanical Reasoning",
      option1: "Lighter than the surrounding air",
      option2: "heavier than the surrounding air",
      option3: "the same as the surrounding air",
      option4: "None",
      suggestions: [
        "construction manager",
        "carpentry",
        "quality control",
        "assembly workers",
        "maintenance workers",
        "aircraft engineer",
        "machine operative",
      ],

      score: 5,
      answerText: "Lighter than the surrounding air",
      answerIndex: 0,
    },
    {
      questionText: "Choose an answer from the list below: ",
      questionImage: "https://i.postimg.cc/yNDTTRfq/Q4.png",
      questionType: "Mechanical Reasoning",
      option1: "4mF ",
      option2: "3mF ",
      option3: "5mF ",
      option4: "Impossible to answer",
      suggestions: [
        "construction manager",
        "carpentry",
        "quality control",
        "assembly workers",
        "maintenance workers",
        "aircraft engineer",
        "machine operative",
      ],

      score: 5,
      answerText: "Impossible to answer",
      answerIndex: 3,
    },
    {
      questionText:
        "The Pacific yew is an evergreen tree that grows in the Pacific Northwest. The Pacific yew has a fleshy, poisonous fruit. Recently, taxol, a substance found in the bark of the Pacific yew, was discovered to be a promising new anticancer drug. ",
      questionImage: "",
      questionType: "Verbal Reasoning",
      option1: "Taxol is poisonous when taken by healthy people.",
      option2: "Taxol has cured people from various diseases. ",
      option3: "People should not eat the fruit of the Pacific yew. ",
      option4:
        "The Pacific yew was considered worthless until taxol was discovered",
      suggestions: [
        "business",
        "law",
        "media",
        "public relation",
        "proof reader",
        "journalism",
        "advertising",
        "civil service",
      ],

      score: 5,
      answerText: "People should not eat the fruit of the Pacific yew.",
      answerIndex: 2,
    },
    {
      questionText:
        "The miser gazed ...... at the pile of gold coins in front of him. ",
      questionImage: "",
      questionType: "Verbal Reasoning",
      option1: "avidly",
      option2: "admiringly ",
      option3: "thoughtfully ",
      option4: "earnestly",
      suggestions: [
        "business",
        "law",
        "media",
        "public relation",
        "proof reader",
        "journalism",
        "advertising",
        "civil service",
      ],

      score: 5,
      answerText: "earnestly",
      answerIndex: 3,
    },
    {
      questionText:
        "If negotiations are to prove fruitful, there must not only be sincerity on each side, but there must also be ...... in the sincerity of the other side. ",
      questionImage: "",
      questionType: "Verbal Reasoning",
      option1: "faith",
      option2: "belief ",
      option3: "substance ",
      option4: "certainty",
      suggestions: [
        "business",
        "law",
        "media",
        "public relation",
        "proof reader",
        "journalism",
        "advertising",
        "civil service",
      ],

      score: 5,
      answerText: "faith",
      answerIndex: 0,
    },
    {
      questionText: "Butterfly → caterpillar : toad →________",
      questionImage: "",
      questionType: "Verbal Reasoning",
      option1: "Tadpole ",
      option2: "Frog ",
      option3: "swamp ",
      option4: "fly",
      suggestions: [
        "business",
        "law",
        "media",
        "public relation",
        "proof reader",
        "journalism",
        "advertising",
        "civil service",
      ],

      score: 5,
      answerText: "Tadpole ",
      answerIndex: 0,
    },
    {
      questionText: " 3 | 8 | 15 | 24 | 35 | ?",
      questionImage: "",
      questionType: "Numerical Reasoning",
      option1: "42 ",
      option2: "36 ",
      option3: "48 ",
      option4: "46",
      suggestions: [
        "computer science",
        "design",
        "laboratory technician",
        "accounting",
        "auditor",
        "tax consultant",
      ],

      score: 5,
      answerText: "36",
      answerIndex: 2,
    },
    {
      questionText:
        "The post office receives a package every 3 minutes, and the mail man delivers 12 packages an hour. If the mail man start working at 08:00, and there are no packages left from the previous day, how long will it take until there will be exactly 100 undelivered packages in the post office?",
      questionImage: "",
      questionType: "Numerical Reasoning",
      option1: "50 minutes ",
      option2: "3 hours and 20 minutes ",
      option3: "6 hours and 40 minutes",
      option4: "12 hours and 30 minutes ",
      suggestions: [
        "computer science",
        "design",
        "laboratory technician",
        "accounting",
        "auditor",
        "tax consultant",
      ],

      score: 5,
      answerText: "12 hours and 30 minutes ",
      answerIndex: 3,
    },
    {
      questionText: "Convert 0.111 to a fraction",
      questionImage: "",
      questionType: "Numerical Reasoning",
      option1: "1/10",
      option2: "1/11 ",
      option3: "1/9 ",
      option4: "11/1100",
      suggestions: [
        "computer science",
        "design",
        "laboratory technician",
        "accounting",
        "auditor",
        "tax consultant",
      ],

      score: 5,
      answerText: "1/9",
      answerIndex: 2,
    },
    {
      questionText:
        "The sum of three numbers is 98. If the ratio of the first to second is 2 :3 and that of the second to the third is 5 : 8, then the second number is:",
      questionImage: "",
      questionType: "Numerical Reasoning",
      option1: "20",
      option2: "30",
      option3: "48",
      option4: "58",
      suggestions: [
        "computer science",
        "design",
        "laboratory technician",
        "accounting",
        "auditor",
        "tax consultant",
      ],

      score: 5,
      answerText: "30",
      answerIndex: 1,
    },
    {
      questionText: "Which figure is next in the series?",
      questionImage: "https://i.postimg.cc/qBFQzjQs/q1.png",
      questionType: "Abstract Reasoning",
      option1: "A",
      option2: "B",
      option3: "C",
      option4: "D",
      suggestions: [
        "computer science",
        "design",
        "law",
        "architecture",
        "animations",
        "construction",
        "carpentry",
        "laboratory technician",
        "mechanics",
      ],

      score: 5,
      answerText: "B",
      answerIndex: 1,
    },
    {
      questionText: "Which figure completes the grid?",
      questionImage: "https://i.postimg.cc/XNrmHZzg/2.png",
      questionType: "Abstract Reasoning",
      option1: "A",
      option2: "B",
      option3: "C",
      option4: "D",
      suggestions: [
        "computer science",
        "design",
        "law",
        "architecture",
        "animations",
        "construction",
        "carpentry",
        "laboratory technician",
        "mechanics",
      ],

      score: 5,
      answerText: "A",
      answerIndex: 0,
    },
    {
      questionText: "Identify the missing square.",
      questionImage: "https://i.postimg.cc/28cqzKwY/3.png",
      questionType: "Abstract Reasoning",
      option1: "A",
      option2: "B",
      option3: "C",
      option4: "D",
      suggestions: [
        "computer science",
        "design",
        "law",
        "architecture",
        "animations",
        "construction",
        "carpentry",
        "laboratory technician",
        "mechanics",
      ],

      score: 5,
      answerText: "C",
      answerIndex: 2,
    },
  ],
};
